module.exports.join = require('./join')
module.exports.leave = require('./leave')
module.exports.search = require('./search')
module.exports.start = require('./start')
module.exports.pause = require('./pause')
module.exports.skip = require('./skip')
module.exports.volume = require('./volume')
module.exports.test = require('./test')
